### PR TITLE
Hybridau + c-goosen python3 port

### PR DESCRIPTION
**Pull request by c-goosen**
Combined the https://github.com/HybridAU/opencanary with my own.

Been trying to keep python2 support.

Still busy testing and porting, just creating PR as you mentioned looking at Porting already.

Thanks
Goose.

### CODE REVIEW

**Comment by jayjb** [comment]
Hey @c-goosen, @HybridAU,

Im going through tests now. Im trying to see if we can keep it as python 2 compatible as possible. So essentially this will happen in two steps:
1) ensure that the new code for python3 works with python3 (once we are happy with that, we can put a fork in it in a branch for now - it will end up in master though eventually)
2) once python3 port is complete; Ill go and patch where needed to try keep python 2 supported.

Does this sound like a good approach? Please let me know what you think.

**Comment by c-goosen** [comment]
@jayjb agreed. I tried to keep python2 compatibility as much as possible. Obviously we want people to move over thanks to 2020, but we can't just pull the rug under people's feet.

Sounds like a good approach.

**Comment by c-goosen** [comment]
@jayjb Should we add some tools for automated testing? Specifically tox, black, bandit, flake8, etc.?

**Comment by jayjb** [comment]
@c-goosen, great. I made a few changes already, but its going nicely! 👍 

I like the idea of adding that automated testing, but I would only be able to help with that after we have completed (and are happy) with our porting+compat. 

Ill keep you updated as I go. I see the one hurdle is Twisted (py2 vs py3). Different Twisted services expect byte strings while others expect text strings so going to have to be careful with that. Let me know if you have anymore thoughts 🤘

**Comment by c-goosen** [comment]
Look I can PR some of the Tox and other things. Add travis-ci etc.

**Comment by c-goosen** [comment]
Yeah twisted is one hurdle. I had some trouble with all the bash scripts starting services. I am still looking into it as well so will let you know if I find anything.

**Comment by c-goosen** [comment]
Tox is useful as you can setup py2 and py3 environments and then run them together.

**Comment by c-goosen** [comment]
If I have some time Ill add tox, bandit, black and flake8 to this PR and you can have a look. It won't conflict with your changes in code hopefully.

**Comment by HybridAU** [comment]
@jayjb That approach sounds like a good plan to me. @c-goosen having travis-ci would be amazing :-)

**Comment by jayjb** [comment]
hey @HybridAU, @c-goosen,

Sorry for the delay. I was away for the BH and DEFCON. Ill get right back onto this. 

@c-goosen: all those integrations sound great, I just haven't used all of them yet. Ill take a look at Tox so long because im doing that manually kinda at the moment

**Pull request merged**
