### PR TITLE
Adds WebhookHandler to logging options

### PR DESCRIPTION
**Pull request by joewesch**

### CODE REVIEW

**Review by HybridAU — COMMENTED** [review]
I've reviewed this change too and it looks good to me

**Review by jayjb — CHANGES_REQUESTED** [review]
Hi @joewesch,

Firstly, Im so sorry about the delay. Please would you mind emailing me at: jay [at] thinkst [dot] com. 

I'm going through all your PRs now (and their great). This one I have a question about. Can we rename it to Webhook instead of RequestHandler (unless this is different to a webhook and I've misread it).

The thinking here is that a webhook is more easily understood and more widely known. I think it is a great feature though so thank you very much.

**Comment by joewesch** [comment]
Sure, let me rename it. I named it Request just because it uses the python requests library under the hood, but yeah webhook is also appropriate.

**Review by jayjb — APPROVED** [review]
Thanks so much for making these changes.

**Pull request merged**
