### PR TITLE
Update based on Ubuntu 14.04.4 LTS experiences. Minor formatting chan…

### PR DESCRIPTION
**Pull request by leesoh**
…ges.

### CODE REVIEW

**Comment by thinkst** [comment]
Hey @leesoh,

Thanks again for taking the time to put in these changes. It's intended that that most of the commands are not run as root (eg. git clone). It's likely that in your setup, the instructions are being run in a directory not owned by user account you're using. Try running the steps in the user's home directory. That should remove the need for sudo powers.

**Comment by leesoh** [comment]
Ahh, sorry for the confusion then. I assumed that you'd want to be setting up your venv somewhere other than ~ (/opt, for example). Am I missing something regarding the command to launch opencanary (/path/to/... vs opencanaryd)?

**Comment by thinkst** [comment]
Both ways would work - you're not missing anything. `opencanaryd` would work if the virtualenv is still activated and `path/to/venv/../opencanaryd` would work regardless.

**Comment by leesoh** [comment]
Hm. I must've missed something then because after installing in virtualenv, opencanaryd isn't present on the ```path/to/venv/bin...``` with virtualenv activated. I'll do some more poking around and see if I can find out what I'm missing.

**Pull request closed without merging**
