### PR TITLE
Addding Python 3 support

### PR DESCRIPTION
**Pull request by HybridAU**
I created issue #33 a while ago, adding Python 3 support. At the time I'd done some work but never created a pull request and then my version got a bit out of date. So I've come at it again. 

I've got the core of opencanary working in Python 3 but some modules don't work in Python 3 yet. All the changes I've made are backwards compatible.

I've written a few crude unit tests and I've tested in manually in Python 2.7 to ensure it still works in python 2.x and the telnet, ssh, http and ftp modules are also working in Python 3.

EDIT: added support for Python 3 in the http module as well.

### CODE REVIEW

**Comment by thinkst** [comment]
Hey @HybridAU,

Thanks so much for this. Ill be going through it over the next few days. (this is really awesome, thanks!)

**Comment by etiennemunnich** [comment]
Any update on progress?

**Comment by DonRichards** [comment]
Is this going to get merged?

**Comment by sweeder** [comment]
Make this happen. I’ve been having trouble connecting with my windows 10 laptop

**Comment by jayjb** [comment]
Hi folks,

Sorry for the delay. We have a python3 branch that you can check out. Basically that is where the Python3 supported version of OpenCanary is at the moment. Currently there are 2 modules left to port: SMB and portscan. Once these are done, ill merge into master. 

Sorry again for the delay.

**Comment by sweeder** [comment]
No worries. Take your time guys build py3 support and anything else to the best of y’all abilities. Do not apologize people, we love & appreciate what you guys are doing, just keep up the good work & have some fun with it!

**Pull request merged**
