### PR TITLE
Adds environment variable substitution to the config file

### PR DESCRIPTION
**Pull request by joewesch**

### CODE REVIEW

**Review by HybridAU — COMMENTED** [review]
I've reviewed these changes and I think it's a good idea, I like the way you use `os.path.expandvars` to get environment variables.

**Review by jayjb — APPROVED** [review]

**Comment by jayjb** [comment]
@joewesch and @HybridAU, did you test the environment variable substitution on Python3 as well? 

When i first tested these changes, I could've sworn it worked for both python2 and python3 but I cannot get the honeycred to work with python3 now. 

Please can you confirm for me.

**Comment by joewesch** [comment]
I've only ever used python3 and my current local environment is using Dockerfile.latest which is 3.7.

**Comment by joewesch** [comment]
Are you on Windows? I included a note in the docs, but you need to surround your variables with `%` instead of using the singular `$` in front.

**Comment by jayjb** [comment]
@joewesch; nope. This is on ubuntu 22.04 currently.. I'm quite sure its stupidity on my part because im fairly certain I had it working previously

**Comment by joewesch** [comment]
In that case the other possible troubleshooting steps I would recommend are:

- The obvious: ensure `echo $VARIABLE` responds with the value
- If you are using `sudo` make sure to use `sudo -E` to pass your current environment variables to the escalated user.

**Comment by jayjb** [comment]
Thanks @joewesch. There was an encoding mismatch.

**Pull request merged**
