### PR TITLE
Add https

### LINKED ISSUE #214: from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
we keep getting this error from today when we tried to build opencanary using docker image
from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
from twisted.internet import error, udp, tcp

### PR DESCRIPTION
**Pull request by HybridAU**
This PR adds HTTPS as an option addressing issue #146 it also bumps the version of cryptography which fixes #214

It's pretty much a straight copy of the HTTP module, but with SSL.

Users can provide their own certificate/key at the path from the `https.certificate` and `https.key` settings, by default  `/etc/ssl/opencanary/opencanary.pem`, `/etc/ssl/opencanary/opencanary.key` respectively. 

Or if no certificate is provided, a self signed certificate is generated to look like a Synology NAS.

### CODE REVIEW

**Review by jayjb — CHANGES_REQUESTED** [review]
This is such a great addition. Can I please just ask that we import the `StaticNoDirListing`, `RedirectCustomHeaders`, `BasicLogin`, `Error` from the `http` modules. This means we would only need to fix one place for bug affecting both `https` and `http`

**Comment by jayjb** [comment]
Sorry for the delay by the way.

**Comment by HybridAU** [comment]
That sounds like a good idea, I'll update the PR in the next couple of days, and no worries about the delay I'm pretty busy with life too :+1:

**Comment by HybridAU** [comment]
I've updated this PR to import from the http module :slightly_smiling_face:

**Review by jayjb — APPROVED** [review]

**Pull request merged**
