### PR TITLE
Created Dockerfile

### PR DESCRIPTION
**Pull request by joubin**
I added a docker file for easier adoption for those working in a container based environment.

### CODE REVIEW

**Comment by joubin** [comment]
Added a run file to make onboarding easier.

**Comment by jayjb** [comment]
Hi @joubin,

This looks great. I just wanna give it a test run before i accept. Thanks so much though!

**Comment by frozenfoxx** [comment]
Was anything holding this up? Was going to add my own Dockerfile but saw this PR.

**Comment by jayjb** [comment]
Hi @frozenfoxx,

Sorry this PR has taken so long. We were deciding on whether Opencanary docker should be a separate repo. But i dont see that as a great way to go. Ill recheck this soon. Sorry for the wait (@joubin)

**Comment by jayjb** [comment]
Hi @joubin,

Just wanted to check where you felt this file should go. Im battling to find it in your branch in the `opencanary` directory. I suspect creating a `/docker` directory would be best

**Comment by joubin** [comment]
@jayjb - I think `/docker` makes a lot of sense. I can push another merge tonight if you like that folder structure better.

**Comment by jayjb** [comment]
@joubin, sorry for the intermittent responses. Yes please. I think if we move it into another folder, we can also get folks adding to it there.

**Comment by joubin** [comment]
@jayjb  - After doing some research, I do think leaving the `Dockerfile` in the root makes the most sense. 

For example, in the updates I've made, there are two `Dockerfile`s. One is intended to build off of the Pypi, but the other uses files from the current branch. In that example, I can't `COPY ../setup.py setup.py` in the `Dockerfile` given the scope that `docker build` runs at. 

Let me know if this makes sense.

**Comment by DennisLoska** [comment]
@joubin I have never worked with opencanary before and was thinking of integrating it in my current server where I am running some containers already. Is your solution difficult to setup? The readme only says to start the container and nothing more about it. Thanks!

**Comment by joubin** [comment]
Hey @DennisLoska 

Running it in the container or outside is no different. In fact, just because you are already running containers doesn't directly mean you should run this in a container. 

That said, I think running this in a container is cleaner (not more or less secure). 

So once you run the container, depending on what service you want to use, you just open the respective port. 

For my setup, I have a few containers running all of the time. I also have this container running where I run externally exposed instances. For example, I have a container that gets TLS certs from LetsEncrypt. When its not the one using port 80 externally, open canary takes over. Its fun to see everyone knocking on my door 👍

**Comment by DennisLoska** [comment]
@joubin Thank you that sounds great! I already got my webserver exposed to port 80 so for me the main concern is with SSH :lock:

**Comment by joubin** [comment]
@DennisLoska  - There is an SSH profile in the configuration. I highly recommend it. But... that said - I would look at a requiting keys (not passwords) for authentication and using fail2ban to ban IPs that fail authentication. 

In that model, you know that authentication will always succeed (if its you since you have your own private key) or it will fail surely for those without the key. Their IP then can be banned for some amount of time. For me, they get banned for SSH access and not http/s access for ever.

**Review by jayjb — APPROVED** [review]

**Comment by jayjb** [comment]
Hi @joubin,

Sorry for the delay. Would you mind emailing me at `jay [at] thinkst [dot] com` please? We would love to send you something for your contribution to our project.

**Comment by DennisLoska** [comment]
@joubin Thanks for the support. Yeah I never use SSH with passwords - my standard apporach is a combination of using keys and fail2ban when setting up  a new server or environment and usually it's Ubuntu so I throw in some ufw settings, too. I ain't no DevOps guy, but I guess these 3 things are the least I can do.

Also nice, that this issue got merged, so I can use it officially :+1:

**Pull request merged**
