### PR TITLE
Update logger.py

### PR DESCRIPTION
**Pull request by prashantvidja**
Hello,

I have added "import hpfeeds" for use hpfeed logger in logger.py file.

Without this is not working.

Thanks

### CODE REVIEW

**Comment by thinkst** [comment]
Hey @prashantvidja,

Sorry for the delay and thanks for the PR. Would you mind adding `hpfeeds` to the `setup.py` as a requirement. I'd gladly accept it after that. 

Thanks again.

**Comment by prashantvidja** [comment]
Hello,

I have added `hpfeeds` on `setup.py` as requirement.

Thanks

**Comment by thinkst** [comment]
Hey @prashantvidja,

I dont see that addition of `hpfeeds` in the `setup.py` currently in this commit (or PR)? Do you mind making sure you have committed it please. Sorry for the delay.

**Comment by thinkst** [comment]
hey @prashantvidja,

Please add the `setup.py` with the `hpfeeds` to this commit and i can accept it. 

Thanks again for helping us with this!

**Comment by prashantvidja** [comment]
I have tried but i have no idea how can i push that code on thread.

**Comment by prashantvidja** [comment]
Can you please do it for me.

**Comment by prashantvidja** [comment]
I have changed Please check that.
Thanks

**Comment by thinkst** [comment]
@prashantvidja thanks so much for this! We really appreciate your participation in this project.

**Pull request merged**
